version: '3.1'
services:
  springboot:
    image: jeevanchiru/java-web-app:2
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
  mongodb:
    image: mongo
    volume:
    - Backup:/data/db
networks:
  mavenappbridge:
volume:
  Backup
    
